# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3cf6491bc39c0fe5a7b3af815bb73c7cd11fe129541e81c6694a825c62badc6af32eee2a8eecf5371934e65c9a6bc6e96825a88b221cd8b9b0c14afdce5c4c0

test:
  secret_key_base: 3421e433009e17fc6aca2e92084fb5994be725994f2a37136fdb632b96e0f2ab0e6d485f376dcf980f5ec836611c0e57bf5b78491129d390eb542d6c043cf8a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
